// IMPORTS BLOCK (with Helmet import added)
import React, { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Github, Zap, Settings, Shield, ChevronRight, Loader, Star, DollarSign, Layout, Users } from "lucide-react";
import { motion, useScroll, useTransform, useSpring, useInView } from "framer-motion";
import TokensCounterContainer from "../components/TokensCounterContainer";
import NexusRBXHeader from "../components/NexusRBXHeader";
import NexusRBXFooter from "../components/NexusRBXFooter";
import { auth } from "../firebase";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { getEntitlements } from "../lib/billing";
import SubscribeTabContainer from "../components/SubscribeTabContainer";
import { Helmet } from "react-helmet";

// Container Component
export default function NexusRBXHomepageContainer() {
  const [inputValue, setInputValue] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [currentTypewriterIndex, setCurrentTypewriterIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [user, setUser] = useState(null);
  const [tokenInfo, setTokenInfo] = useState(null);
  const [tokenLoading, setTokenLoading] = useState(false);

  const navigate = useNavigate();

  // Listen for Firebase authentication state
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
    });
    return () => unsubscribe();
  }, []);

  // Fetch token info when user logs in
  useEffect(() => {
    if (!user) {
      setTokenInfo(null);
      return;
    }
    setTokenLoading(true);
    getEntitlements()
      .then((data) => {
        setTokenInfo(data);
      })
      .catch(() => {
        setTokenInfo(null);
      })
      .finally(() => setTokenLoading(false));
  }, [user]);

  const handleLogin = () => {
    navigate("/signin");
  };

  const handleLogout = async () => {
    await signOut(auth);
    setUser(null);
    navigate("/signin");
  };

  const handleInputChange = (e) => {
    setInputValue(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setError("");
    if (!inputValue.trim()) return;

    // Pass prompt to /ai page, but do not trigger generation
    navigate("/ai", {
      state: {
        initialPrompt: inputValue.trim(),
        aiResult: null
      }
    });
    setInputValue("");
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsTyping(true);
    }, 1500);

    return () => clearTimeout(timer);
  }, []);

  const exampleOutputs = [
    {
      id: 1,
      prompt: "Create a modern sci-fi main menu",
      output:
        '-- Generated by NexusRBX UI Engine\nlocal MainMenu = Instance.new("ScreenGui")\nlocal Background = Instance.new("Frame")\nBackground.BackgroundColor3 = Color3.fromRGB(10, 10, 20)\nBackground.Size = UDim2.new(1, 0, 1, 0)',
      language: "lua",
    },
    {
      id: 2,
      prompt: "Generate a tactical RPG HUD",
      output:
        'local HUD = Instance.new("ScreenGui")\nlocal HealthBar = Instance.new("Frame")\nHealthBar.BackgroundColor3 = Color3.fromRGB(255, 50, 50)\nHealthBar.Size = UDim2.new(0, 200, 0, 20)',
      language: "lua",
    },
    {
      id: 3,
      prompt: "Build a shop system with categories",
      output:
        'local ShopUI = Instance.new("ScreenGui")\nlocal ScrollingFrame = Instance.new("ScrollingFrame")\nScrollingFrame.CanvasSize = UDim2.new(0, 0, 2, 0)\nScrollingFrame.ScrollBarThickness = 8',
      language: "lua",
    },
  ];

  useEffect(() => {
    if (isTyping) {
      const interval = setInterval(() => {
        setCurrentTypewriterIndex((prev) => {
          if (prev < exampleOutputs.length - 1) {
            return prev + 1;
          } else {
            return 0;
          }
        });
      }, 2000);

      return () => clearInterval(interval);
    }
  }, [isTyping, exampleOutputs.length]);

  const navLinks = [
    { id: 1, text: "Docs", href: "/docs" },
    { id: 3, text: "Ai Console", href: "/ai" },
    { id: 4, text: "Account", href: "/settings" },
    { id: 5, text: "API (Soon)", href: "#", comingSoon: true },
    { id: 2, text: "Discord (Soon)", href: "#", external: false },
  ];

  const featureCards = [
    {
      id: 1,
      title: "AI UI Builder",
      description: "Generate professional Roblox interfaces—from main menus to complex HUDs—in seconds. Fully customizable and optimized for all platforms.",
      icon: Layout,
      gradient: "from-purple-600 to-pink-500",
      button: { text: "Build UI", href: "/ai" },
    },
    {
      id: 2,
      title: "Premium",
      description: "Unlock Nexus-5 (GPT-5.2) AI, high-limit generations, and priority support. Access exclusive UI components and advanced scripting features.",
      icon: null,
      gradient: "from-cyan-500 to-blue-600",
      button: { text: "Subscribe", href: "/subscribe" },
      isSubscribeTab: true,
    },
    {
      id: 3,
      title: "Smart Scripting",
      description: "Write complex Luau game logic with ease. Our AI understands Roblox's API deeply, helping you build features faster than ever.",
      icon: Zap,
      gradient: "from-pink-500 to-purple-600",
      button: { text: "Start Scripting", href: "/ai" },
    },
  ];

  const footerLinks = [
    { id: 1, text: "Terms of Service", href: "/terms" },
    { id: 2, text: "Privacy Policy", href: "/privacy" },
    { id: 3, text: "Contact", href: "/contact" },
    { id: 4, text: "Discord (Soon)", href: "#" },
  ];

  const handleNavClick = (href, external) => (e) => {
    e.preventDefault();
    if (external) {
      window.open(href, "_blank", "noopener noreferrer");
    } else {
      navigate(href);
    }
  };

  return (
    <NexusRBXHomepage
      inputValue={inputValue}
      handleInputChange={handleInputChange}
      handleSubmit={handleSubmit}
      navLinks={navLinks}
      featureCards={featureCards}
      exampleOutputs={exampleOutputs}
      footerLinks={footerLinks}
      isTyping={isTyping}
      currentTypewriterIndex={currentTypewriterIndex}
      handleNavClick={handleNavClick}
      navigate={navigate}
      loading={loading}
      error={error}
      user={user}
      handleLogin={handleLogin}
      handleLogout={handleLogout}
      tokenInfo={tokenInfo}
      tokenLoading={tokenLoading}
    />
  );
}

// UI Component
function NexusRBXHomepage({
  inputValue,
  handleInputChange,
  handleSubmit,
  navLinks,
  featureCards,
  exampleOutputs,
  footerLinks,
  isTyping,
  currentTypewriterIndex,
  handleNavClick,
  navigate,
  loading,
  error,
  user,
  handleLogin,
  handleLogout,
  tokenInfo,
  tokenLoading
}) {
  const containerRef = useRef(null);

  const randomUsers = [
    { letter: "J", color: "from-purple-500 to-indigo-500" },
    { letter: "A", color: "from-cyan-500 to-blue-500" },
    { letter: "T", color: "from-pink-500 to-rose-500" },
    { letter: "K", color: "from-emerald-500 to-teal-500" },
    { letter: "S", color: "from-orange-500 to-amber-500" },
  ];

  return (
    // OPENING OF TOP-LEVEL CONTAINER WITH <Helmet> INSERTED
    <div ref={containerRef} className="min-h-screen bg-[#0D0D0D] text-white font-sans flex flex-col relative">
      {/* Side Decorations */}
      <div className="fixed inset-y-0 left-0 w-1 bg-gradient-to-b from-transparent via-[#9b5de5]/20 to-transparent z-20" />
      <div className="fixed inset-y-0 right-0 w-1 bg-gradient-to-b from-transparent via-[#00f5d4]/20 to-transparent z-20" />
      
      <div className="fixed inset-y-0 left-4 w-px bg-white/5 z-0 hidden lg:block" />
      <div className="fixed inset-y-0 right-4 w-px bg-white/5 z-0 hidden lg:block" />

      {/* Background Blobs */}
      <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-[#9b5de5]/10 blur-[120px] animate-pulse" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-[#00f5d4]/10 blur-[120px] animate-pulse" style={{ animationDelay: '2s' }} />
      </div>
      <Helmet>
        <title>NexusRBX — AI Roblox UI Builder & Script Generator</title>
        <meta name="description" content="NexusRBX is the ultimate AI-powered Roblox UI builder and script generator. Design stunning interfaces and complex game logic in seconds with artificial intelligence. Try our AI UI Engine today." />
        <link rel="canonical" href={typeof window !== "undefined" ? window.location.origin : "https://nexusrbx.com"} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="NexusRBX" />
        <meta property="og:title" content="NexusRBX — AI Roblox UI Builder & Script Generator" />
        <meta property="og:description" content="The best AI-powered Roblox UI builder and script generator. Generate professional interfaces and Luau code instantly. Fast, optimized, and built for Roblox creators." />
        <meta property="og:url" content={typeof window !== "undefined" ? window.location.href : "https://nexusrbx.com"} />
        <meta property="og:image" content="/social-card.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="NexusRBX — AI Roblox UI Builder & Script Generator" />
        <meta name="twitter:description" content="NexusRBX is the #1 AI Roblox UI builder and script generator. Instantly create professional interfaces and developer tools with artificial intelligence." />
        <meta name="twitter:image" content="/social-card.png" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <meta name="keywords" content="AI Roblox UI builder, Roblox script generator, Roblox UI design, Roblox scripting, Roblox AI, generate Roblox UI, Roblox developer tools, Roblox Premium, Luau code generator, Roblox UI engine" />
        <meta name="author" content="NexusRBX" />
        <meta name="theme-color" content="#0D0D0D" />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context":"https://schema.org",
            "@type":"Organization",
            "name":"NexusRBX",
            "url":"https://nexusrbx.com",
            "logo":"/logo.png",
            "sameAs":[ "https://discord.gg/", "https://github.com/TravelTable/nexusairbx" ]
          })}
        </script>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context":"https://schema.org",
            "@type":"SoftwareApplication",
            "name":"NexusRBX",
            "applicationCategory":"DeveloperApplication",
            "operatingSystem":"Web",
            "description":"NexusRBX is an AI-powered Roblox UI builder and scripting platform. Instantly generate professional interfaces and developer tools with artificial intelligence.",
            "image":"/social-card.png",
            "offers":{ "@type":"Offer", "price":"14.99", "priceCurrency":"USD" }
          })}
        </script>
      </Helmet>

      {/* Header */}
      <NexusRBXHeader
        navLinks={navLinks}
        handleNavClick={handleNavClick}
        navigate={navigate}
        user={user}
        handleLogin={handleLogin}
        tokenInfo={tokenInfo}
        tokenLoading={tokenLoading}
      />

      <main className="flex-grow">
        {/* HERO SECTION BLOCK WITH H1 + PARAGRAPH CHANGES AND HERO IMAGE PLACEHOLDER */}
        <section className="min-h-[70vh] flex items-center justify-center py-20 px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: "easeOut" }}
            className="max-w-6xl mx-auto text-center space-y-8"
          >
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-sm font-medium text-[#00f5d4] mb-4">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#00f5d4] opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-[#00f5d4]"></span>
              </span>
              Nexus-5 (GPT-5.2) Engine Now Live
            </div>

            <h1 className="text-4xl md:text-7xl font-bold tracking-tight bg-gradient-to-r from-[#9b5de5] via-[#f15bb5] to-[#00f5d4] text-transparent bg-clip-text leading-tight">
              The Ultimate AI UI Builder <br className="hidden md:block" /> & Script Generator
            </h1>
            <p className="text-lg md:text-2xl text-gray-400 max-w-3xl mx-auto leading-relaxed">
              Design stunning interfaces and complex game logic in seconds. NexusRBX turns your ideas into production-ready <a href="/ai" className="underline decoration-[#9b5de5]/60 hover:decoration-[#9b5de5] text-white">Lua code</a> for Roblox Studio.
            </p>

            {/* Social Proof Spot */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5 }}
              className="flex flex-col items-center gap-4 pt-4"
            >
              <div className="flex -space-x-3">
                {randomUsers.map((u, i) => (
                  <div key={i} className={`w-10 h-10 rounded-full border-2 border-[#0D0D0D] bg-gradient-to-br ${u.color} flex items-center justify-center text-xs font-bold shadow-lg`}>
                    {u.letter}
                  </div>
                ))}
                <div className="w-10 h-10 rounded-full border-2 border-[#0D0D0D] bg-gray-800 flex items-center justify-center text-[10px] font-bold text-gray-400 shadow-lg">
                  +5k
                </div>
              </div>
              <p className="text-sm font-medium text-gray-400">
                Helping <span className="text-white font-bold">5,000+</span> Roblox Developers
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3, duration: 0.8 }}
              className="max-w-4xl mx-auto mt-12 relative group"
            >
              <div className="absolute -inset-1 bg-gradient-to-r from-[#9b5de5] to-[#00f5d4] rounded-2xl blur opacity-20 group-hover:opacity-40 transition duration-1000 group-hover:duration-200"></div>
              <img
                src="/ai-preview.png"
                alt="AI Generation Preview"
                className="relative w-full rounded-2xl border border-white/10 shadow-2xl"
              />
            </motion.div>
            <form
              onSubmit={handleSubmit}
              className="mt-12 flex flex-col md:flex-row gap-3 max-w-2xl mx-auto relative z-20"
            >
              <input
                type="text"
                value={inputValue}
                onChange={handleInputChange}
                placeholder="Describe a UI or script idea..."
                className="flex-grow px-4 py-3 rounded-lg bg-gray-900/60 border border-gray-700 focus:border-[#9b5de5] focus:outline-none focus:ring-2 focus:ring-[#9b5de5]/50 transition-all duration-300"
                disabled={loading}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                  }
                }}
                aria-label="Type your Roblox UI or script idea"
                autoComplete="off"
                name="roblox-idea"
              />
              <button
                type="submit"
                className="px-6 py-3 rounded-lg bg-gradient-to-r from-[#9b5de5] to-[#00f5d4] text-white font-medium hover:shadow-lg hover:shadow-[#9b5de5]/20 transform hover:translate-y-[-2px] transition-all duration-300 flex items-center justify-center"
                disabled={!inputValue.trim() || loading}
                aria-label="Generate with AI"
              >
                {loading ? (
                  <>
                    <Loader className="mr-2 h-5 w-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    Generate with AI
                    <ChevronRight className="ml-2 h-5 w-5" />
                  </>
                )}
              </button>
            </form>
            {error && (
              <div className="text-red-400 mt-2" role="alert">{error}</div>
            )}
            <div className="text-sm text-gray-500 mt-2">
              <span>Describe your idea and press <b>Enter</b> or click "Generate with AI"</span>
            </div>
          </motion.div>
        </section>

        {/* FEATURES SECTION OPENING WITH H2 AND SAMPLE CARD WITH IMAGE PLACEHOLDER */}
        <section className="py-24 px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl md:text-4xl font-bold text-center mb-16 bg-gradient-to-r from-[#9b5de5] to-[#00f5d4] text-transparent bg-clip-text">
              Powerful AI Tools for Roblox Creators
            </h2>
          </motion.div>
          <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
            {featureCards.map((card, index) => (
              <motion.article
                key={card.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                whileHover={{ y: -5 }}
                className="relative overflow-hidden rounded-2xl bg-white/[0.02] backdrop-blur-md border border-white/10 p-8 hover:border-white/20 transition-all duration-500 group flex flex-col"
                itemScope
                itemType="https://schema.org/Service"
              >
                <div
                  className={`absolute inset-0 bg-gradient-to-br ${card.gradient} opacity-0 group-hover:opacity-10 transition-opacity duration-500`}
                ></div>
                <div className="absolute -inset-1 bg-gradient-to-r from-transparent via-[#9b5de5]/20 to-transparent opacity-0 group-hover:opacity-100 blur-xl transition-opacity duration-500"></div>

                <div className="relative flex-1">
                  {card.isSubscribeTab ? (
                    <>
                      <SubscribeTabContainer
                        onSubscribe={() => navigate("/subscribe")}
                        isSubscribed={false}
                        className="!bg-transparent !border-none !shadow-none p-0"
                      />
                      <img
                        src="/feature-premium.webp"
                        alt="Premium AI features for Roblox development"
                        width="800"
                        height="600"
                        loading="lazy"
                        decoding="async"
                        className="rounded-lg border border-gray-800 mb-4 w-full"
                      />
                    </>
                  ) : (
                    <>
                      <div
                        className={`w-12 h-12 rounded-full bg-gradient-to-br ${card.gradient} flex items-center justify-center mb-4`}
                      >
                        {card.icon && <card.icon className="h-6 w-6 text-white" />}
                      </div>
                      {/* Optional image placeholder for Script AI and Secure Testing */}
                      {card.id === 1 && (
                        <img
                          src="/feature-script-ai.webp"
                          alt="Roblox script generator preview"
                          width="800"
                          height="600"
                          loading="lazy"
                          decoding="async"
                          className="rounded-lg border border-gray-800 mb-4 w-full"
                        />
                      )}
                      {card.id === 3 && (
                        <img
                          src="/feature-secure.webp"
                          alt="Secure testing environment for Roblox mods"
                          width="800"
                          height="600"
                          loading="lazy"
                          decoding="async"
                          className="rounded-lg border border-gray-800 mb-4 w-full"
                        />
                      )}
                      <h3 className="text-xl font-bold mb-2" itemProp="name">{card.title}</h3>
                      <p className="text-gray-400" itemProp="description">{card.description}</p>
                      <button
                        className="mt-6 px-4 py-2 rounded-lg bg-gradient-to-r from-[#9b5de5] to-[#00f5d4] text-white font-medium hover:shadow-lg hover:shadow-[#9b5de5]/20 transform hover:translate-y-[-2px] transition-all duration-300 flex items-center justify-center"
                        onClick={() => navigate(card.button.href)}
                        type="button"
                        aria-label={`Learn more about ${card.title} for Roblox scripting`}
                      >
                        {card.button.text}
                        <ChevronRight className="ml-2 h-4 w-4" />
                      </button>
                    </>
                  )}
                </div>
              </motion.article>
            ))}
          </div>
        </section>


        {/* Community Creations (Coming Soon) */}
        <section className="py-24 px-4 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#9b5de5]/5 to-transparent pointer-events-none" />
          <div className="max-w-6xl mx-auto relative">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-4 bg-gradient-to-r from-[#9b5de5] to-[#00f5d4] text-transparent bg-clip-text">
                Community Creations
              </h2>
              <p className="text-gray-400 text-lg max-w-2xl mx-auto">
                A curated gallery of the most impressive UIs and scripts built by the NexusRBX community.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 opacity-40 grayscale pointer-events-none select-none">
              {[1, 2, 3, 4].map((i) => (
                <div key={i} className="aspect-video rounded-xl bg-gray-900 border border-gray-800 flex items-center justify-center">
                  <Layout className="w-8 h-8 text-gray-700" />
                </div>
              ))}
            </div>

            <div className="absolute inset-0 flex items-center justify-center pt-20">
              <div className="px-8 py-4 rounded-2xl bg-black/60 backdrop-blur-xl border border-white/10 shadow-2xl transform rotate-[-2deg]">
                <span className="text-2xl md:text-3xl font-black tracking-tighter bg-gradient-to-r from-[#9b5de5] to-[#00f5d4] text-transparent bg-clip-text uppercase">
                  Coming Soon
                </span>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <NexusRBXFooter
        footerLinks={footerLinks}
        handleNavClick={handleNavClick}
        navigate={navigate}
      />

      {/* CSS Animations */}
      <style jsx>{`
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        .animate-fade-in {
          animation: fadeIn 1s ease-out forwards;
        }
      `}</style>
    </div>
  );
}
