// IMPORTS BLOCK (with Helmet import added)
import React, { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Github, Zap, Settings, Shield, ChevronRight, Loader, Star, DollarSign, Layout, Users, Code, Cpu, Download } from "lucide-react";
import { motion, useScroll, useTransform, useSpring, useInView, AnimatePresence } from "framer-motion";
import TokensCounterContainer from "../components/TokensCounterContainer";
import NexusRBXHeader from "../components/NexusRBXHeader";
import NexusRBXFooter from "../components/NexusRBXFooter";
import { auth } from "../firebase";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { getEntitlements } from "../lib/billing";
import SubscribeTabContainer from "../components/SubscribeTabContainer";
import { Helmet } from "react-helmet";
import HeroSection from "../components/home/HeroSection";
import FeaturesSection from "../components/home/FeaturesSection";
import CommunityCreationsSection from "../components/home/CommunityCreationsSection";

// Container Component
export default function NexusRBXHomepageContainer() {
  const [inputValue, setInputValue] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [currentTypewriterIndex, setCurrentTypewriterIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [user, setUser] = useState(null);
  const [tokenInfo, setTokenInfo] = useState(null);
  const [tokenLoading, setTokenLoading] = useState(false);

  const navigate = useNavigate();

  // Listen for Firebase authentication state
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
    });
    return () => unsubscribe();
  }, []);

  // Fetch token info when user logs in
  useEffect(() => {
    if (!user) {
      setTokenInfo(null);
      return;
    }
    setTokenLoading(true);
    getEntitlements()
      .then((data) => {
        setTokenInfo(data);
      })
      .catch(() => {
        setTokenInfo(null);
      })
      .finally(() => setTokenLoading(false));
  }, [user]);

  const handleLogin = () => {
    navigate("/signin");
  };

  const handleLogout = async () => {
    await signOut(auth);
    setUser(null);
    navigate("/signin");
  };

  const handleInputChange = (e) => {
    setInputValue(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setError("");
    if (!inputValue.trim()) return;

    // Pass prompt to /ai page, but do not trigger generation
    navigate("/ai", {
      state: {
        initialPrompt: inputValue.trim(),
        aiResult: null
      }
    });
    setInputValue("");
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsTyping(true);
    }, 1500);

    return () => clearTimeout(timer);
  }, []);

  const exampleOutputs = [
    {
      id: 1,
      prompt: "Create a modern sci-fi main menu",
      output:
        '-- Generated by NexusRBX UI Engine\nlocal MainMenu = Instance.new("ScreenGui")\nlocal Background = Instance.new("Frame")\nBackground.BackgroundColor3 = Color3.fromRGB(10, 10, 20)\nBackground.Size = UDim2.new(1, 0, 1, 0)',
      language: "lua",
    },
    {
      id: 2,
      prompt: "Generate a tactical RPG HUD",
      output:
        'local HUD = Instance.new("ScreenGui")\nlocal HealthBar = Instance.new("Frame")\nHealthBar.BackgroundColor3 = Color3.fromRGB(255, 50, 50)\nHealthBar.Size = UDim2.new(0, 200, 0, 20)',
      language: "lua",
    },
    {
      id: 3,
      prompt: "Build a shop system with categories",
      output:
        'local ShopUI = Instance.new("ScreenGui")\nlocal ScrollingFrame = Instance.new("ScrollingFrame")\nScrollingFrame.CanvasSize = UDim2.new(0, 0, 2, 0)\nScrollingFrame.ScrollBarThickness = 8',
      language: "lua",
    },
  ];

  useEffect(() => {
    if (isTyping) {
      const interval = setInterval(() => {
        setCurrentTypewriterIndex((prev) => {
          if (prev < exampleOutputs.length - 1) {
            return prev + 1;
          } else {
            return 0;
          }
        });
      }, 2000);

      return () => clearInterval(interval);
    }
  }, [isTyping, exampleOutputs.length]);

  const navLinks = [
    { id: 1, text: "Docs", href: "/docs" },
    { id: 3, text: "Ai Console", href: "/ai" },
    { id: 4, text: "Account", href: "/settings" },
    { id: 6, text: "Plugin (Soon)", href: "#", comingSoon: true },
    { id: 5, text: "API (Soon)", href: "#", comingSoon: true },
    { id: 2, text: "Discord (Soon)", href: "#", external: false },
  ];

  const featureCards = [
    {
      id: 1,
      title: "AI UI Builder",
      description: "Generate professional Roblox interfaces—from main menus to complex HUDs—in seconds. Fully customizable and optimized for all platforms.",
      icon: Layout,
      gradient: "from-purple-600 to-pink-500",
      button: { text: "Build UI", href: "/ai" },
    },
    {
      id: 2,
      title: "Premium",
      description: "Unlock Nexus-5 (GPT-5.2) AI, high-limit generations, and priority support. Access exclusive UI components and advanced scripting features.",
      icon: null,
      gradient: "from-cyan-500 to-blue-600",
      button: { text: "Subscribe", href: "/subscribe" },
      isSubscribeTab: true,
    },
    {
      id: 3,
      title: "Smart Scripting",
      description: "Write complex Luau game logic with ease. Our AI understands Roblox's API deeply, helping you build features faster than ever.",
      icon: Zap,
      gradient: "from-pink-500 to-purple-600",
      button: { text: "Start Scripting", href: "/ai" },
    },
  ];

  const footerLinks = [
    { id: 1, text: "Terms of Service", href: "/terms" },
    { id: 2, text: "Privacy Policy", href: "/privacy" },
    { id: 3, text: "Contact", href: "/contact" },
    { id: 4, text: "Docs", href: "/docs" },
  ];

  const handleNavClick = (href, external) => (e) => {
    e.preventDefault();
    if (external) {
      window.open(href, "_blank", "noopener noreferrer");
    } else {
      navigate(href);
    }
  };

  return (
    <NexusRBXHomepage
      inputValue={inputValue}
      handleInputChange={handleInputChange}
      handleSubmit={handleSubmit}
      navLinks={navLinks}
      featureCards={featureCards}
      exampleOutputs={exampleOutputs}
      footerLinks={footerLinks}
      isTyping={isTyping}
      currentTypewriterIndex={currentTypewriterIndex}
      handleNavClick={handleNavClick}
      navigate={navigate}
      loading={loading}
      error={error}
      user={user}
      handleLogin={handleLogin}
      handleLogout={handleLogout}
      tokenInfo={tokenInfo}
      tokenLoading={tokenLoading}
    />
  );
}

// UI Component
function NexusRBXHomepage({
  inputValue,
  handleInputChange,
  handleSubmit,
  navLinks,
  featureCards,
  exampleOutputs,
  footerLinks,
  isTyping,
  currentTypewriterIndex,
  handleNavClick,
  navigate,
  loading,
  error,
  user,
  handleLogin,
  handleLogout,
  tokenInfo,
  tokenLoading
}) {
  const containerRef = useRef(null);

  const advertisedTools = [
    {
      id: 1,
      title: "Pro-Grade UI Engine",
      description: "Generates production-ready hierarchies using UIAspectRatioConstraints and CanvasGroups. Optimized for AutomaticSize responsiveness.",
      icon: Layout,
      position: "top-[5%] -left-8 xl:-left-32",
      delay: 0.2,
    },
    {
      id: 2,
      title: "Deep Luau Integration",
      description: "Implements Strict Type Checking and the modern Task library. Built-in support for Signal patterns and ProfileService.",
      icon: Code,
      position: "top-[20%] -right-8 xl:-right-32",
      delay: 0.4,
    },
    {
      id: 3,
      title: "Nexus-5 Neural Core",
      description: "Powered by GPT-5.2, fine-tuned for Parallel Luau and Actor patterns. Mastery of complex CFrame math and Spatial Queries.",
      icon: Cpu,
      position: "bottom-[15%] -left-4 xl:-left-24",
      delay: 0.6,
    },
    {
      id: 4,
      title: "Studio-Ready Workflow",
      description: "Instant JSON manifest extraction for Rojo or direct Luau injection. Handles AssetId mapping and TweenService easing.",
      icon: Download,
      position: "bottom-[0%] -right-4 xl:-right-24",
      delay: 0.8,
    },
  ];

  const randomUsers = [
    { letter: "J", color: "from-purple-500 to-indigo-500" },
    { letter: "A", color: "from-cyan-500 to-blue-500" },
    { letter: "T", color: "from-pink-500 to-rose-500" },
    { letter: "K", color: "from-emerald-500 to-teal-500" },
    { letter: "S", color: "from-orange-500 to-amber-500" },
  ];

  return (
    // OPENING OF TOP-LEVEL CONTAINER WITH <Helmet> INSERTED
    <div ref={containerRef} className="min-h-screen bg-[#0D0D0D] text-white font-sans flex flex-col relative">
      {/* Side Decorations */}
      <div className="fixed inset-y-0 left-0 w-1 bg-gradient-to-b from-transparent via-[#9b5de5]/20 to-transparent z-20" />
      <div className="fixed inset-y-0 right-0 w-1 bg-gradient-to-b from-transparent via-[#00f5d4]/20 to-transparent z-20" />
      
      <div className="fixed inset-y-0 left-4 w-px bg-white/5 z-0 hidden lg:block" />
      <div className="fixed inset-y-0 right-4 w-px bg-white/5 z-0 hidden lg:block" />

      {/* Background Blobs */}
      <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-[#9b5de5]/10 blur-[120px] animate-pulse" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-[#00f5d4]/10 blur-[120px] animate-pulse" style={{ animationDelay: '2s' }} />
      </div>
      <Helmet>
        <title>NexusRBX — AI Roblox UI Builder & Script Generator</title>
        <meta name="description" content="NexusRBX is the ultimate AI-powered Roblox UI builder and script generator. Design stunning interfaces and complex game logic in seconds with artificial intelligence. Try our AI UI Engine today." />
        <link rel="canonical" href={typeof window !== "undefined" ? window.location.origin : "https://nexusrbx.com"} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="NexusRBX" />
        <meta property="og:title" content="NexusRBX — AI Roblox UI Builder & Script Generator" />
        <meta property="og:description" content="The best AI-powered Roblox UI builder and script generator. Generate professional interfaces and Luau code instantly. Fast, optimized, and built for Roblox creators." />
        <meta property="og:url" content={typeof window !== "undefined" ? window.location.href : "https://nexusrbx.com"} />
        <meta property="og:image" content="/social-card.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="NexusRBX — AI Roblox UI Builder & Script Generator" />
        <meta name="twitter:description" content="NexusRBX is the #1 AI Roblox UI builder and script generator. Instantly create professional interfaces and developer tools with artificial intelligence." />
        <meta name="twitter:image" content="/social-card.png" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <meta name="keywords" content="AI Roblox UI builder, Roblox script generator, Roblox UI design, Roblox scripting, Roblox AI, generate Roblox UI, Roblox developer tools, Roblox Premium, Luau code generator, Roblox UI engine" />
        <meta name="author" content="NexusRBX" />
        <meta name="theme-color" content="#0D0D0D" />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context":"https://schema.org",
            "@type":"Organization",
            "name":"NexusRBX",
            "url":"https://nexusrbx.com",
            "logo":"/logo.png",
            "sameAs":[ "https://discord.gg/", "https://github.com/TravelTable/nexusairbx" ]
          })}
        </script>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context":"https://schema.org",
            "@type":"SoftwareApplication",
            "name":"NexusRBX",
            "applicationCategory":"DeveloperApplication",
            "operatingSystem":"Web",
            "description":"NexusRBX is an AI-powered Roblox UI builder and scripting platform. Instantly generate professional interfaces and developer tools with artificial intelligence.",
            "image":"/social-card.png",
            "offers":{ "@type":"Offer", "price":"14.99", "priceCurrency":"USD" }
          })}
        </script>
      </Helmet>

      {/* Header */}
      <NexusRBXHeader
        navLinks={navLinks}
        handleNavClick={handleNavClick}
        navigate={navigate}
        user={user}
        handleLogin={handleLogin}
        tokenInfo={tokenInfo}
        tokenLoading={tokenLoading}
      />

      <main className="flex-grow">
        <HeroSection
          advertisedTools={advertisedTools}
          randomUsers={randomUsers}
          handleSubmit={handleSubmit}
          inputValue={inputValue}
          handleInputChange={handleInputChange}
          loading={loading}
          error={error}
        />

        <FeaturesSection
          featureCards={featureCards}
          navigate={navigate}
        />

        <CommunityCreationsSection />
      </main>

      {/* Footer */}
      <NexusRBXFooter
        footerLinks={footerLinks}
        handleNavClick={handleNavClick}
        navigate={navigate}
      />

      {/* CSS Animations */}
      <style>{`
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        .animate-fade-in {
          animation: fadeIn 1s ease-out forwards;
        }
      `}</style>
    </div>
  );
}
