import React, { useCallback, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Plus,
  Search,
  Wand2,
  Sparkles,
  Image as ImageIcon,
  Hash,
  ClipboardList,
  X,
  AlertTriangle,
} from "lucide-react";

/**
 * PlanningBoardPage (MVP scaffold)
 * - No server calls yet (we'll wire to Firestore/API after components are solid)
 * - No-code board for Roblox UI building
 * - Stores imageIds + itemIds + behavior intents
 * - Has an "AI clarification" flow (asks for missing required data instead of guessing)
 */

/** ---------- Helpers ---------- */
function uid(prefix = "id") {
  return `${prefix}_${Math.random().toString(16).slice(2)}_${Date.now().toString(16)}`;
}

function normalizeRbxAssetId(input) {
  const raw = String(input || "").trim();
  if (!raw) return "";
  if (raw.startsWith("rbxassetid://")) return raw;
  // if user pastes just digits
  if (/^\d+$/.test(raw)) return `rbxassetid://${raw}`;
  return raw; // allow other valid formats if they exist
}

function isImageIdLike(v) {
  const s = String(v || "").trim();
  return /^rbxassetid:\/\/\d+$/.test(s) || /^\d+$/.test(s);
}

/** ---------- Defaults (local only for now) ---------- */
const DEFAULT_COLUMNS = [
  { id: "layer_screen", title: "ScreenGui Layer" },
  { id: "layer_main", title: "Main Frame" },
  { id: "layer_overlay", title: "Overlay / Modal" },
  { id: "layer_toasts", title: "Toasts / Notifications" },
];

// A small starter set so the page isn't empty on first load.
const DEFAULT_ITEMS = [
  {
    id: uid("item"),
    type: "Frame",
    name: "MainFrame",
    title: "Main Frame Container",
    columnId: "layer_main",
    description: "Primary container for the UI.",
    tags: ["layout"],
    imageIds: [],
    itemIds: ["MainFrame"],
    // behavior is intent-based; AI turns this into code later
    behaviors: [],
    requirements: [], // can be auto-generated by validation/AI
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: uid("item"),
    type: "ImageButton",
    name: "PlayButton",
    title: "Play Button",
    columnId: "layer_main",
    description: "Tap to start the game.",
    tags: ["cta"],
    imageIds: [{ id: "", label: "Button image", required: true }],
    itemIds: ["PlayButton"],
    behaviors: [
      {
        id: uid("beh"),
        trigger: "OnClick",
        action: "FireEvent",
        target: "PlayGame",
        notes: "Ask AI whether this is a BindableEvent or a RemoteEvent.",
      },
    ],
    requirements: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: uid("item"),
    type: "TextButton",
    name: "SettingsButton",
    title: "Settings Button",
    columnId: "layer_main",
    description: "Opens settings modal.",
    tags: ["navigation"],
    imageIds: [],
    itemIds: ["SettingsButton"],
    behaviors: [
      {
        id: uid("beh"),
        trigger: "OnClick",
        action: "OpenUI",
        target: "SettingsModal",
      },
    ],
    requirements: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: uid("item"),
    type: "Frame",
    name: "SettingsModal",
    title: "Settings Modal",
    columnId: "layer_overlay",
    description: "Modal panel with toggles (sound, music, etc).",
    tags: ["modal"],
    imageIds: [],
    itemIds: ["SettingsModal"],
    behaviors: [
      {
        id: uid("beh"),
        trigger: "OnOpen",
        action: "FocusTrap",
        target: "SettingsModal",
        notes: "AI should implement modal blocking + close path.",
      },
    ],
    requirements: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

const COMPONENT_TYPES = [
  "ScreenGui",
  "Frame",
  "TextLabel",
  "TextButton",
  "ImageLabel",
  "ImageButton",
  "ScrollingFrame",
  "UIListLayout",
  "UIGridLayout",
  "UIPadding",
  "UICorner",
  "UIStroke",
];

function validateItem(item) {
  const blocking = [];
  const clarifications = [];

  // Required asset rule: ImageButton/ImageLabel must have at least 1 valid ImageId
  if (item.type === "ImageButton" || item.type === "ImageLabel") {
    const ids = (item.imageIds || []).map((x) => String(x?.id || "").trim()).filter(Boolean);
    const hasValid = ids.some((v) => isImageIdLike(v) || /^rbxassetid:\/\/\d+$/.test(v));
    if (!hasValid) {
      blocking.push({
        itemId: item.id,
        field: "imageIds",
        reason: `${item.type} requires an ImageId (rbxassetid://123...).`,
      });
    }
  }

  // Modal sanity: must have a close path
  if ((item.tags || []).includes("modal")) {
    const hasClose = (item.behaviors || []).some(
      (b) =>
        (b.trigger === "OnClick" && (b.action === "CloseUI" || b.action === "ToggleUI")) ||
        b.action === "CloseUI"
    );
    if (!hasClose) {
      clarifications.push({
        itemId: item.id,
        question:
          "This looks like a modal. Should it close when clicking outside, pressing ESC, or via a close button?",
      });
    }
  }

  // FireEvent needs event type clarification
  const hasFireEvent = (item.behaviors || []).some((b) => b.action === "FireEvent");
  if (hasFireEvent) {
    clarifications.push({
      itemId: item.id,
      question:
        "You used FireEvent. Should this be a RemoteEvent (client->server) or BindableEvent (local-only)?",
    });
  }

  return { blocking, clarifications };
}

/** ---------- Small UI bits (inline for now; we'll extract to components next) ---------- */
function Pill({ children }) {
  return (
    <span className="inline-flex items-center rounded-full bg-white/5 px-2 py-0.5 text-[11px] text-gray-200 ring-1 ring-white/10">
      {children}
    </span>
  );
}

function IconButton({ title, onClick, children, className = "" }) {
  return (
    <button
      type="button"
      title={title}
      onClick={onClick}
      className={`inline-flex items-center justify-center rounded-xl bg-white/5 px-3 py-2 text-gray-200 ring-1 ring-white/10 hover:bg-white/10 ${className}`}
    >
      {children}
    </button>
  );
}

/** ---------- Page ---------- */
export default function PlanningBoardPage() {
  const navigate = useNavigate();

  // Later: board list, board selection, persistence, multi-board.
  const [boardName, setBoardName] = useState("Roblox UI Board");
  const [columns, setColumns] = useState(DEFAULT_COLUMNS);
  const [items, setItems] = useState(DEFAULT_ITEMS);

  const [search, setSearch] = useState("");
  const deferredSearch = search; // (keep simple; you can use useDeferredValue later)

  const [selectedItemId, setSelectedItemId] = useState(null);
  const selectedItem = useMemo(
    () => items.find((i) => i.id === selectedItemId) || null,
    [items, selectedItemId]
  );

  // AI clarification modal state
  const [aiGate, setAiGate] = useState({
    open: false,
    itemId: null,
    blocking: [],
    clarifications: [],
  });

  // Drag/drop state (simple HTML5)
  const dragItemIdRef = useRef(null);

  const filteredItems = useMemo(() => {
    const q = String(deferredSearch || "").trim().toLowerCase();
    if (!q) return items;
    return items.filter((it) => {
      const hay = [
        it.title,
        it.name,
        it.type,
        it.description,
        ...(it.tags || []),
        ...((it.itemIds || []).map(String)),
        ...((it.imageIds || []).map((x) => String(x?.id || ""))),
      ]
        .join(" ")
        .toLowerCase();
      return hay.includes(q);
    });
  }, [items, deferredSearch]);

  const itemsByColumn = useMemo(() => {
    const map = new Map();
    for (const c of columns) map.set(c.id, []);
    for (const it of filteredItems) {
      const list = map.get(it.columnId) || [];
      list.push(it);
      map.set(it.columnId, list);
    }
    // stable sort by updatedAt (newest first)
    for (const [k, list] of map.entries()) {
      list.sort((a, b) => (b.updatedAt || 0) - (a.updatedAt || 0));
      map.set(k, list);
    }
    return map;
  }, [columns, filteredItems]);

  const createItem = useCallback(() => {
    const id = uid("item");
    const next = {
      id,
      type: "Frame",
      name: `NewFrame_${id.slice(-4)}`,
      title: "New Component",
      columnId: columns[0]?.id || "layer_main",
      description: "",
      tags: [],
      imageIds: [],
      itemIds: [],
      behaviors: [],
      requirements: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    };
    setItems((prev) => [next, ...prev]);
    setSelectedItemId(id);
  }, [columns]);

  const updateItem = useCallback((itemId, patch) => {
    setItems((prev) =>
      prev.map((it) =>
        it.id === itemId
          ? {
              ...it,
              ...patch,
              updatedAt: Date.now(),
            }
          : it
      )
    );
  }, []);

  const moveItemToColumn = useCallback((itemId, columnId) => {
    updateItem(itemId, { columnId });
  }, [updateItem]);

  const onDragStart = useCallback((itemId) => {
    dragItemIdRef.current = itemId;
  }, []);

  const onDropColumn = useCallback(
    (columnId) => {
      const itemId = dragItemIdRef.current;
      dragItemIdRef.current = null;
      if (!itemId) return;
      moveItemToColumn(itemId, columnId);
    },
    [moveItemToColumn]
  );

  const addBehavior = useCallback(() => {
    if (!selectedItem) return;
    const next = {
      id: uid("beh"),
      trigger: "OnClick",
      action: "OpenUI",
      target: "",
      notes: "",
    };
    updateItem(selectedItem.id, { behaviors: [...(selectedItem.behaviors || []), next] });
  }, [selectedItem, updateItem]);

  const addImageRef = useCallback(() => {
    if (!selectedItem) return;
    const next = { id: "", label: "Image", required: selectedItem.type.includes("Image") };
    updateItem(selectedItem.id, { imageIds: [...(selectedItem.imageIds || []), next] });
  }, [selectedItem, updateItem]);

  const addItemIdRef = useCallback(() => {
    if (!selectedItem) return;
    updateItem(selectedItem.id, { itemIds: [...(selectedItem.itemIds || []), ""] });
  }, [selectedItem, updateItem]);

  const runAiOnSelected = useCallback(() => {
    if (!selectedItem) return;

    const { blocking, clarifications } = validateItem(selectedItem);

    // If anything is missing, open the AI gate instead of guessing.
    if (blocking.length || clarifications.length) {
      setAiGate({
        open: true,
        itemId: selectedItem.id,
        blocking,
        clarifications,
      });
      return;
    }

    // Placeholder: later this will call your /api/generate route with:
    // - board snapshot
    // - selected item
    // - linked script/project + base version
    // and will create a new version.
    alert("AI is ready to implement (no missing requirements). Next step: wire server + versioning.");
  }, [selectedItem]);

  const applyAiGateAnswers = useCallback(() => {
    const it = items.find((x) => x.id === aiGate.itemId);
    if (!it) {
      setAiGate({ open: false, itemId: null, blocking: [], clarifications: [] });
      return;
    }
    // Re-validate after edits (still local; server-side validation later too)
    const { blocking, clarifications } = validateItem(it);
    if (blocking.length) {
      setAiGate((prev) => ({ ...prev, blocking, clarifications }));
      return;
    }
    setAiGate({ open: false, itemId: null, blocking: [], clarifications: [] });
    alert("Requirements satisfied. Next: send to AI generator and create a new version.");
  }, [aiGate.itemId, items]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#0b0b12] via-[#090915] to-[#070711] text-white">
      {/* Top Bar */}
      <div className="sticky top-0 z-30 border-b border-white/10 bg-black/30 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-3">
          <IconButton title="Back" onClick={() => navigate("/ai")} className="px-2">
            <ArrowLeft className="h-5 w-5" />
          </IconButton>

          <div className="flex min-w-0 flex-1 items-center gap-3">
            <div className="min-w-0">
              <div className="text-xs text-gray-400">Roblox UI Planning Board</div>
              <input
                value={boardName}
                onChange={(e) => setBoardName(e.target.value)}
                className="w-full truncate bg-transparent text-lg font-semibold outline-none placeholder:text-gray-600"
                placeholder="Board name..."
              />
            </div>

            <div className="hidden items-center gap-2 md:flex">
              <Pill>no-code UI</Pill>
              <Pill>AI compiles to LocalScript</Pill>
              <Pill>replicable</Pill>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <div className="relative hidden md:block">
              <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" />
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-72 rounded-xl bg-white/5 py-2 pl-10 pr-3 text-sm text-gray-200 ring-1 ring-white/10 placeholder:text-gray-500 focus:ring-2 focus:ring-[#9b5de5]"
                placeholder="Search components, ids, tags..."
              />
            </div>

            <IconButton title="New Component" onClick={createItem}>
              <Plus className="h-5 w-5" />
            </IconButton>

            <button
              type="button"
              onClick={runAiOnSelected}
              className="inline-flex items-center gap-2 rounded-xl bg-[#9b5de5] px-4 py-2 text-sm font-semibold text-white shadow-sm hover:brightness-110"
            >
              <Wand2 className="h-4 w-4" />
              AI Implement
            </button>
          </div>
        </div>
      </div>

      {/* Main layout */}
      <div className="mx-auto grid max-w-7xl grid-cols-1 gap-4 px-4 py-4 md:grid-cols-[1fr_380px]">
        {/* Board */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
          <div className="mb-3 flex items-center justify-between">
            <div className="text-sm text-gray-300">
              Drag components between layers. Click a card to edit details.
            </div>
            <div className="flex items-center gap-2">
              <Pill>{items.length} components</Pill>
              <Pill>{columns.length} layers</Pill>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">
            {columns.map((col) => {
              const list = itemsByColumn.get(col.id) || [];
              return (
                <div
                  key={col.id}
                  onDragOver={(e) => e.preventDefault()}
                  onDrop={() => onDropColumn(col.id)}
                  className="rounded-2xl border border-white/10 bg-black/20 p-3"
                >
                  <div className="mb-2 flex items-center justify-between">
                    <div className="text-sm font-semibold text-gray-100">{col.title}</div>
                    <Pill>{list.length}</Pill>
                  </div>

                  <div className="space-y-2">
                    {list.map((it) => {
                      const isSelected = it.id === selectedItemId;
                      const v = validateItem(it);
                      const hasBlockers = v.blocking.length > 0;

                      return (
                        <div
                          key={it.id}
                          draggable
                          onDragStart={() => onDragStart(it.id)}
                          onClick={() => setSelectedItemId(it.id)}
                          className={`cursor-pointer rounded-2xl border p-3 transition ${
                            isSelected
                              ? "border-[#9b5de5] bg-white/10"
                              : "border-white/10 bg-white/5 hover:bg-white/10"
                          }`}
                        >
                          <div className="flex items-start justify-between gap-2">
                            <div className="min-w-0">
                              <div className="truncate text-sm font-semibold text-white">
                                {it.title || "Untitled"}
                              </div>
                              <div className="truncate text-xs text-gray-400">
                                {it.type} - {it.name}
                              </div>
                            </div>

                            {hasBlockers ? (
                              <span
                                title="Missing required data"
                                className="inline-flex items-center gap-1 rounded-full bg-red-500/10 px-2 py-1 text-[11px] text-red-200 ring-1 ring-red-400/20"
                              >
                                <AlertTriangle className="h-3.5 w-3.5" />
                                Fix
                              </span>
                            ) : (
                              <span
                                title="OK"
                                className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-1 text-[11px] text-emerald-200 ring-1 ring-emerald-400/20"
                              >
                                <Sparkles className="h-3.5 w-3.5" />
                                Ready
                              </span>
                            )}
                          </div>

                          {it.description ? (
                            <div className="mt-2 line-clamp-2 text-xs text-gray-300">
                              {it.description}
                            </div>
                          ) : null}

                          <div className="mt-2 flex flex-wrap gap-1">
                            {(it.tags || []).slice(0, 4).map((t) => (
                              <Pill key={t}>{t}</Pill>
                            ))}
                            {(it.tags || []).length > 4 ? <Pill>+{it.tags.length - 4}</Pill> : null}
                          </div>
                        </div>
                      );
                    })}

                    {list.length === 0 ? (
                      <div className="rounded-xl border border-dashed border-white/10 p-3 text-xs text-gray-500">
                        Drop components here
                      </div>
                    ) : null}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Inspector (right panel) */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-4">
          {!selectedItem ? (
            <div className="text-sm text-gray-300">
              Select a component card to edit details (visual customization + ids + behaviors).
            </div>
          ) : (
            <div className="space-y-4">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="text-xs text-gray-400">Selected component</div>
                  <div className="truncate text-lg font-semibold text-white">
                    {selectedItem.title || "Untitled"}
                  </div>
                  <div className="text-xs text-gray-400">
                    {selectedItem.type} - {selectedItem.name}
                  </div>
                </div>
                <IconButton title="Close" onClick={() => setSelectedItemId(null)} className="px-2">
                  <X className="h-5 w-5" />
                </IconButton>
              </div>

              {/* Basics */}
              <div className="space-y-2 rounded-2xl border border-white/10 bg-black/20 p-3">
                <div className="text-sm font-semibold text-gray-100">Basics</div>
                <div className="grid grid-cols-1 gap-2">
                  <label className="text-xs text-gray-400">
                    Title
                    <input
                      value={selectedItem.title || ""}
                      onChange={(e) => updateItem(selectedItem.id, { title: e.target.value })}
                      className="mt-1 w-full rounded-xl bg-white/5 px-3 py-2 text-sm text-gray-200 ring-1 ring-white/10 focus:ring-2 focus:ring-[#9b5de5]"
                    />
                  </label>

                  <label className="text-xs text-gray-400">
                    Name (Roblox instance name)
                    <input
                      value={selectedItem.name || ""}
                      onChange={(e) => updateItem(selectedItem.id, { name: e.target.value })}
                      className="mt-1 w-full rounded-xl bg-white/5 px-3 py-2 text-sm text-gray-200 ring-1 ring-white/10 focus:ring-2 focus:ring-[#9b5de5]"
                    />
                  </label>

                  <label className="text-xs text-gray-400">
                    Type
                    <select
                      value={selectedItem.type || "Frame"}
                      onChange={(e) => updateItem(selectedItem.id, { type: e.target.value })}
                      className="mt-1 w-full rounded-xl bg-white/5 px-3 py-2 text-sm text-gray-200 ring-1 ring-white/10 focus:ring-2 focus:ring-[#9b5de5]"
                    >
                      {COMPONENT_TYPES.map((t) => (
                        <option key={t} value={t} className="bg-[#0b0b12]">
                          {t}
                        </option>
                      ))}
                    </select>
                  </label>

                  <label className="text-xs text-gray-400">
                    Description (what it should do)
                    <textarea
                      value={selectedItem.description || ""}
                      onChange={(e) => updateItem(selectedItem.id, { description: e.target.value })}
                      rows={4}
                      className="mt-1 w-full rounded-xl bg-white/5 px-3 py-2 text-sm text-gray-200 ring-1 ring-white/10 focus:ring-2 focus:ring-[#9b5de5]"
                      placeholder="Explain intent. AI will convert this to code."
                    />
                  </label>

                  <label className="text-xs text-gray-400">
                    Tags (comma separated)
                    <input
                      value={(selectedItem.tags || []).join(", ")}
                      onChange={(e) =>
                        updateItem(selectedItem.id, {
                          tags: e.target.value
                            .split(",")
                            .map((s) => s.trim())
                            .filter(Boolean),
                        })
                      }
                      className="mt-1 w-full rounded-xl bg-white/5 px-3 py-2 text-sm text-gray-200 ring-1 ring-white/10 focus:ring-2 focus:ring-[#9b5de5]"
                      placeholder="modal, layout, navigation..."
                    />
                  </label>
                </div>
              </div>

              {/* Image IDs */}
              <div className="space-y-2 rounded-2xl border border-white/10 bg-black/20 p-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm font-semibold text-gray-100">
                    <ImageIcon className="h-4 w-4 text-gray-300" />
                    Image IDs
                  </div>
                  <IconButton title="Add Image ID" onClick={addImageRef}>
                    <Plus className="h-4 w-4" />
                  </IconButton>
                </div>

                {(selectedItem.imageIds || []).length === 0 ? (
                  <div className="text-xs text-gray-500">
                    Add image IDs if this component uses images (rbxassetid://...).
                  </div>
                ) : (
                  <div className="space-y-2">
                    {(selectedItem.imageIds || []).map((img, idx) => (
                      <div key={`${selectedItem.id}_img_${idx}`} className="rounded-xl border border-white/10 bg-white/5 p-2">
                        <div className="flex items-center gap-2">
                          <input
                            value={img.label || ""}
                            onChange={(e) => {
                              const next = [...(selectedItem.imageIds || [])];
                              next[idx] = { ...next[idx], label: e.target.value };
                              updateItem(selectedItem.id, { imageIds: next });
                            }}
                            className="w-40 rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10"
                            placeholder="Label"
                          />
                          <input
                            value={img.id || ""}
                            onChange={(e) => {
                              const next = [...(selectedItem.imageIds || [])];
                              next[idx] = { ...next[idx], id: normalizeRbxAssetId(e.target.value) };
                              updateItem(selectedItem.id, { imageIds: next });
                            }}
                            className="flex-1 rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10"
                            placeholder="rbxassetid://123456"
                          />
                          <button
                            type="button"
                            className="rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10 hover:bg-white/10"
                            onClick={() => {
                              const next = [...(selectedItem.imageIds || [])];
                              next.splice(idx, 1);
                              updateItem(selectedItem.id, { imageIds: next });
                            }}
                          >
                            <X className="h-4 w-4" />
                          </button>
                        </div>
                        <div className="mt-1 flex items-center gap-2 text-[11px] text-gray-400">
                          <Pill>{img.required ? "required" : "optional"}</Pill>
                          {String(img.id || "").trim() ? (
                            isImageIdLike(img.id) ? (
                              <span className="text-emerald-200">valid</span>
                            ) : (
                              <span className="text-amber-200">check format</span>
                            )
                          ) : (
                            <span className="text-red-200">missing</span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Item IDs */}
              <div className="space-y-2 rounded-2xl border border-white/10 bg-black/20 p-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm font-semibold text-gray-100">
                    <Hash className="h-4 w-4 text-gray-300" />
                    Item IDs
                  </div>
                  <IconButton title="Add Item ID" onClick={addItemIdRef}>
                    <Plus className="h-4 w-4" />
                  </IconButton>
                </div>

                {(selectedItem.itemIds || []).length === 0 ? (
                  <div className="text-xs text-gray-500">
                    Add any extra IDs (component ids, ticket ids, references).
                  </div>
                ) : (
                  <div className="space-y-2">
                    {(selectedItem.itemIds || []).map((v, idx) => (
                      <div key={`${selectedItem.id}_iid_${idx}`} className="flex items-center gap-2">
                        <input
                          value={v || ""}
                          onChange={(e) => {
                            const next = [...(selectedItem.itemIds || [])];
                            next[idx] = e.target.value;
                            updateItem(selectedItem.id, { itemIds: next });
                          }}
                          className="flex-1 rounded-xl bg-white/5 px-3 py-2 text-sm text-gray-200 ring-1 ring-white/10 focus:ring-2 focus:ring-[#9b5de5]"
                          placeholder="e.g. MainFrame, UI-102, component_RightSidebar..."
                        />
                        <IconButton
                          title="Remove"
                          onClick={() => {
                            const next = [...(selectedItem.itemIds || [])];
                            next.splice(idx, 1);
                            updateItem(selectedItem.id, { itemIds: next });
                          }}
                        >
                          <X className="h-4 w-4" />
                        </IconButton>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Behaviors */}
              <div className="space-y-2 rounded-2xl border border-white/10 bg-black/20 p-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm font-semibold text-gray-100">
                    <ClipboardList className="h-4 w-4 text-gray-300" />
                    Behaviors (Intent)
                  </div>
                  <IconButton title="Add Behavior" onClick={addBehavior}>
                    <Plus className="h-4 w-4" />
                  </IconButton>
                </div>

                {(selectedItem.behaviors || []).length === 0 ? (
                  <div className="text-xs text-gray-500">
                    Add intent-based behaviors (AI converts these to Lua).
                  </div>
                ) : (
                  <div className="space-y-2">
                    {(selectedItem.behaviors || []).map((b, idx) => (
                      <div key={b.id} className="rounded-xl border border-white/10 bg-white/5 p-2">
                        <div className="grid grid-cols-1 gap-2">
                          <div className="flex items-center gap-2">
                            <select
                              value={b.trigger || "OnClick"}
                              onChange={(e) => {
                                const next = [...(selectedItem.behaviors || [])];
                                next[idx] = { ...next[idx], trigger: e.target.value };
                                updateItem(selectedItem.id, { behaviors: next });
                              }}
                              className="w-28 rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10"
                            >
                              {["OnClick", "OnHover", "OnOpen", "OnClose", "OnToggle", "OnChange"].map(
                                (t) => (
                                  <option key={t} value={t} className="bg-[#0b0b12]">
                                    {t}
                                  </option>
                                )
                              )}
                            </select>

                            <select
                              value={b.action || "OpenUI"}
                              onChange={(e) => {
                                const next = [...(selectedItem.behaviors || [])];
                                next[idx] = { ...next[idx], action: e.target.value };
                                updateItem(selectedItem.id, { behaviors: next });
                              }}
                              className="w-32 rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10"
                            >
                              {[
                                "OpenUI",
                                "CloseUI",
                                "ToggleUI",
                                "SetState",
                                "FireEvent",
                                "Animate",
                                "PlaySound",
                                "FocusTrap",
                              ].map((a) => (
                                <option key={a} value={a} className="bg-[#0b0b12]">
                                  {a}
                                </option>
                              ))}
                            </select>

                            <input
                              value={b.target || ""}
                              onChange={(e) => {
                                const next = [...(selectedItem.behaviors || [])];
                                next[idx] = { ...next[idx], target: e.target.value };
                                updateItem(selectedItem.id, { behaviors: next });
                              }}
                              className="flex-1 rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10"
                              placeholder="Target (UI name, event name, state key...)"
                            />

                            <button
                              type="button"
                              className="rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10 hover:bg-white/10"
                              onClick={() => {
                                const next = [...(selectedItem.behaviors || [])];
                                next.splice(idx, 1);
                                updateItem(selectedItem.id, { behaviors: next });
                              }}
                            >
                              <X className="h-4 w-4" />
                            </button>
                          </div>

                          <textarea
                            value={b.notes || ""}
                            onChange={(e) => {
                              const next = [...(selectedItem.behaviors || [])];
                              next[idx] = { ...next[idx], notes: e.target.value };
                              updateItem(selectedItem.id, { behaviors: next });
                            }}
                            rows={2}
                            className="w-full rounded-lg bg-white/5 px-2 py-1 text-xs text-gray-200 ring-1 ring-white/10"
                            placeholder="Optional notes for AI (e.g., debounce, remote/bindable, animation preset...)"
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* AI action */}
              <button
                type="button"
                onClick={runAiOnSelected}
                className="w-full rounded-2xl bg-[#9b5de5] py-3 text-sm font-semibold text-white shadow-sm hover:brightness-110"
              >
                AI Implement Selected Component
              </button>

              <div className="text-xs text-gray-500">
                Next: we extract these inspector sections into real components, then wire server calls
                to generate a Roblox LocalScript version from the board snapshot.
              </div>
            </div>
          )}
        </div>
      </div>

      {/* AI Clarification / Gate Modal */}
      {aiGate.open ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
          <div className="w-full max-w-2xl rounded-2xl border border-white/10 bg-[#0b0b12] p-4 shadow-xl">
            <div className="flex items-start justify-between gap-3">
              <div>
                <div className="text-lg font-semibold text-white">AI needs info before generating</div>
                <div className="text-sm text-gray-400">
                  Required data is missing or behavior is ambiguous. Fill these in so the AI doesn't
                  guess and break replication.
                </div>
              </div>
              <IconButton
                title="Close"
                onClick={() => setAiGate({ open: false, itemId: null, blocking: [], clarifications: [] })}
                className="px-2"
              >
                <X className="h-5 w-5" />
              </IconButton>
            </div>

            <div className="mt-4 space-y-3">
              {aiGate.blocking.length ? (
                <div className="rounded-2xl border border-red-400/20 bg-red-500/10 p-3">
                  <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-red-200">
                    <AlertTriangle className="h-4 w-4" />
                    Blocking requirements
                  </div>
                  <ul className="space-y-1 text-sm text-red-100">
                    {aiGate.blocking.map((b, idx) => (
                      <li key={`${b.itemId}_${b.field}_${idx}`} className="text-sm">
                        - {b.reason}
                      </li>
                    ))}
                  </ul>
                  <div className="mt-2 text-xs text-red-200">
                    Fix these in the inspector (Image IDs / required fields) and try again.
                  </div>
                </div>
              ) : null}

              {aiGate.clarifications.length ? (
                <div className="rounded-2xl border border-amber-400/20 bg-amber-500/10 p-3">
                  <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-amber-200">
                    <Sparkles className="h-4 w-4" />
                    Clarifications (recommended)
                  </div>
                  <ul className="space-y-2 text-sm text-amber-100">
                    {aiGate.clarifications.map((c, idx) => (
                      <li key={`${c.itemId}_${idx}`} className="rounded-xl border border-white/10 bg-white/5 p-2">
                        <div className="text-sm">{c.question}</div>
                        <div className="mt-2 text-xs text-gray-300">
                          (We'll turn this into a proper "AI Q&A" component next.)
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}
            </div>

            <div className="mt-4 flex items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => setAiGate({ open: false, itemId: null, blocking: [], clarifications: [] })}
                className="rounded-xl bg-white/5 px-4 py-2 text-sm font-semibold text-gray-200 ring-1 ring-white/10 hover:bg-white/10"
              >
                Not now
              </button>
              <button
                type="button"
                onClick={applyAiGateAnswers}
                className="inline-flex items-center gap-2 rounded-xl bg-[#9b5de5] px-4 py-2 text-sm font-semibold text-white hover:brightness-110"
              >
                <Wand2 className="h-4 w-4" />
                Continue
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
