/**
 * Semantic Nexus icon registry.
 *
 * Primary: @heroicons-animated/react (Heroicons Animated / Aniket Pawar via 21st.dev)
 * State morphs: animated-state-icons (Yad Hakim via 21st.dev)
 *
 * NEVER map to Sparkles, Wand, Brain, Star, or other “AI magic” glyphs.
 * AI / generate / agent → command-line (developer tooling).
 */
import {
  AdjustmentsHorizontalIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpOnSquareIcon,
  ArrowUpTrayIcon,
  ArrowUturnLeftIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  Bars3Icon,
  BellIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ClockIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CreditCardIcon,
  CubeIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  DocumentIcon,
  EllipsisHorizontalIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderIcon,
  FolderPlusIcon,
  HomeIcon,
  InformationCircleIcon,
  LinkIcon as HeroLinkIcon,
  LinkSlashIcon as HeroLinkSlashIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  MoonIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlayCircleIcon,
  PlayIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  RectangleGroupIcon,
  ShieldCheckIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  Square2StackIcon,
  StopCircleIcon,
  StopIcon,
  SunIcon,
  TrashIcon,
  UserCircleIcon,
  WindowIcon,
  XCircleIcon,
  XMarkIcon,
} from "@heroicons-animated/react";

/** Semantic name → Heroicons Animated component. */
export const NEXUS_ICON_COMPONENTS = {
  home: HomeIcon,
  ai: CommandLineIcon,
  "command-line": CommandLineIcon,
  terminal: CommandLineIcon,
  generate: CommandLineIcon,
  agent: CommandLineIcon,
  cpu: CpuChipIcon,
  ui: RectangleGroupIcon,
  window: WindowIcon,
  assets: CubeIcon,
  cube: CubeIcon,
  images: PhotoIcon,
  photo: PhotoIcon,
  image: PhotoIcon,
  scripts: CodeBracketIcon,
  code: CodeBracketIcon,
  files: DocumentIcon,
  document: DocumentIcon,
  projects: FolderIcon,
  folder: FolderIcon,
  history: ClockIcon,
  clock: ClockIcon,
  search: MagnifyingGlassIcon,
  command: CommandLineIcon,
  settings: AdjustmentsHorizontalIcon,
  adjustments: AdjustmentsHorizontalIcon,
  billing: CreditCardIcon,
  usage: ChartBarIcon,
  support: ChatBubbleLeftRightIcon,
  notifications: BellIcon,
  bell: BellIcon,
  account: UserCircleIcon,
  user: UserCircleIcon,

  "studio-connected": HeroLinkIcon,
  link: HeroLinkIcon,
  "studio-disconnected": HeroLinkSlashIcon,
  "link-slash": HeroLinkSlashIcon,
  connect: HeroLinkIcon,
  reconnect: ArrowPathIcon,
  refresh: ArrowPathIcon,
  "apply-studio": ArrowUpOnSquareIcon,
  upload: ArrowUpTrayIcon,
  download: ArrowDownTrayIcon,

  create: PlusIcon,
  plus: PlusIcon,
  "new-project": FolderPlusIcon,
  "folder-plus": FolderPlusIcon,

  close: XMarkIcon,
  menu: Bars3Icon,
  back: ArrowLeftIcon,
  forward: ArrowRightIcon,
  dropdown: ChevronDownIcon,
  chevron: ChevronDownIcon,
  expand: ArrowsPointingOutIcon,
  collapse: ArrowsPointingInIcon,
  inspect: CodeBracketSquareIcon,
  rename: PencilSquareIcon,
  delete: TrashIcon,
  restore: ArrowUturnLeftIcon,
  more: EllipsisHorizontalIcon,

  preview: EyeIcon,
  "preview-hidden": EyeSlashIcon,
  desktop: ComputerDesktopIcon,
  tablet: DeviceTabletIcon,
  mobile: DevicePhoneMobileIcon,
  "zoom-in": MagnifyingGlassPlusIcon,
  "zoom-out": MagnifyingGlassMinusIcon,
  fit: ArrowsPointingOutIcon,

  send: PaperAirplaneIcon,
  attach: PaperClipIcon,
  stop: StopCircleIcon,
  "stop-circle": StopCircleIcon,
  "stop-square": StopIcon,

  copy: Square2StackIcon,
  save: CheckIcon,
  check: CheckIcon,
  "open-external": ArrowTopRightOnSquareIcon,

  video: PlayCircleIcon,
  play: PlayIcon,
  pause: PauseIcon,
  volume: SpeakerWaveIcon,
  muted: SpeakerXMarkIcon,

  success: CheckCircleIcon,
  warning: ExclamationTriangleIcon,
  error: XCircleIcon,
  info: InformationCircleIcon,
  help: QuestionMarkCircleIcon,

  "sign-in": ArrowRightEndOnRectangleIcon,
  "sign-out": ArrowRightStartOnRectangleIcon,
  lock: LockClosedIcon,
  unlock: LockOpenIcon,
  security: ShieldCheckIcon,
  sun: SunIcon,
  moon: MoonIcon,
};

/** Names that use Yad Hakim morphing state icons instead of plain Heroicons. */
export const NEXUS_STATE_ICON_KINDS = {
  copy: "copy",
  download: "download",
  send: "send",
  menu: "menu",
  preview: "eye",
  "preview-hidden": "eye",
  play: "play",
  pause: "play",
  volume: "volume",
  muted: "volume",
  lock: "lock",
  unlock: "lock",
  success: "success-state",
};

export const NEXUS_ICON_SIZES = {
  compact: 14,
  control: 16,
  nav: 18,
  prominent: 20,
};

/** Forbidden “AI magic” names — resolve to tooling icons instead. */
const BANNED_ALIASES = {
  sparkles: "ai",
  sparkle: "ai",
  wand: "ai",
  "wand-sparkles": "ai",
  magic: "ai",
  brain: "cpu",
  stars: "ai",
  star: "check",
};

export function resolveNexusIconName(name) {
  const key = String(name || "")
    .trim()
    .toLowerCase()
    .replace(/[_\s]+/g, "-");
  if (BANNED_ALIASES[key]) return BANNED_ALIASES[key];
  return key;
}
